### ISSUE TITLE
add option for view files tif

### ISSUE THREAD

**Issue by drrc1709** [Alcumus/react-doc-viewer#51]
Add option for view files tif, this library or extesion is the most complete that I found, and I do testing to integrate this with my web app, the option for view docs, no works

**Comment by drrc1709** [comment]
hey friend, how are you?, I need your help, Besides that an error appears when showing some MS Office document, I have tried to use TIFFRenderer to see a .tiff file but in the browser it comes out completely white, it is not displayed, could you help me by indicating how to use this TIFFRenderer or how to use it if use DocViewerRenderers

this is my source

`import React from 'react';
import './App.css';
import DocViewer, { DocViewerRenderers } from "react-doc-viewer";



function App() {
  const docs = [
    //  { uri: "https://www.abbyy.com/media/14009/guide_english.pdf" },
   { uri: require("./docs/Captura de pantalla (1).png") },
    { uri: require("./docs/Doc1.pdf") },
    { uri: require("./docs/test.2p.in.tiff") },
    { uri: require("./docs/5526010020400101110027052018.tiff")}, // Local File
    { uri: require("./docs/Copia de CUADRO_REQ_UGPP - ULTIMO.xlsx")}, // Local File
  ];

  return <div className="container">
    <div className="container">
      <DocViewer
        pluginRenderers={DocViewerRenderers}
        documents={docs}


        theme={{
          primary: "#5296d8",
          secondary: "#000000",
          tertiary: "#5296d899",
          text_primary: "#ffffff",
          text_secondary: "#ffffff",
          text_tertiary: "#00000099",

          disableThemeScrollbar: false,

        }} />
    </div>
  </div>;
}


export default App;
`

**Comment by mattmogford-alcumus** [comment]
Do you have any errors in the console?

**Comment by mattmogford-alcumus** [comment]
Also, If you quickly need a renderer for TIF files, you can create custom renderers.
https://www.npmjs.com/package/react-doc-viewer#custom-renderer

**Comment by drrc1709** [comment]
I did that today but it doesn't work either, look at the code and the view, if you could please help me it would be very helpful and I would be grateful

![imagen](https://user-images.githubusercontent.com/50565417/97503848-cb585880-1943-11eb-8ffb-67e72b72a92a.png)
![imagen](https://user-images.githubusercontent.com/50565417/97503874-d9a67480-1943-11eb-9649-03fdecfa708d.png)

**Comment by mattmogford-alcumus** [comment]
@drrc1709 Would it be possible to provide the exact tif file you are using, this may well be a bug with particular tiff files.
I only have a few example tif files and they render OK.

**Comment by drrc1709** [comment]
[docs.zip](https://github.com/Alcumus/react-doc-viewer/files/5465348/docs.zip)
