### ISSUE TITLE
预览10M左右的word文档，预览不了

### ISSUE THREAD

**Issue by DAHU123** [Alcumus/react-doc-viewer#58]
![image](https://user-images.githubusercontent.com/28329138/98897291-0d59d080-24e6-11eb-8750-c0bca162b6d3.png)
最大支持的文件体积是多大呀？怎么去配置呀？

**Comment by mattmogford-alcumus** [comment]
@DAHU123  Apologies, I can't read what you have written.
But the error looks like a limitation of MSDoc Viewer, they must have a limit on file sizes.
How big is the docx file you are trying to upload?
