### ISSUE TITLE
CORS Policy Issue

### ISSUE THREAD

**Issue by wkungu** [Alcumus/react-doc-viewer#59]
Hi,

I'm getting `Access to fetch at 'https://remote_server/sample.pdf' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.` while loading a remote file. 

How do I resolve this on react-doc-viewer?

Thanks

**Comment by mattmogford-alcumus** [comment]
The issue here is that the server you are trying to access the pdf from, has a CORS policy that doesn't allow your localhost connection to download it's files.
If you are just testing sample files, it would be easier to download the pdf and load it locally.
Or have you're own server hosting the files, with your own CORS policy.

**Comment by drewjulo** [comment]
I host my files using aws and set my cors policy as below

  [
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "HEAD"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": [],
        "MaxAgeSeconds": 3000
    }
]

and i'm still facing this issue

**Comment by mattmogford-alcumus** [comment]
> I host my files using aws and set my cors policy as below
> 
>   [
>     {
>         "AllowedHeaders": [
>             "*"
>         ],
>         "AllowedMethods": [
>             "GET",
>             "HEAD"
>         ],
>         "AllowedOrigins": [
>             "*"
>         ],
>         "ExposeHeaders": [],
>         "MaxAgeSeconds": 3000
>     }
> ]
> 
> and i'm still facing this issue
> 

Hi,
Sorry this would be an aws / server issue

**Comment by wkungu** [comment]
This worked for me.
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "HEAD"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": []
    }
]

**Comment by wkungu** [comment]
This worked for me.
```

[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "HEAD"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": []
    }
] 
```
