### ISSUE TITLE
Is there support for Base 64 files?

### ISSUE THREAD

**Issue by kingeke** [Alcumus/react-doc-viewer#62]

**Comment by david-mcleod** [comment]
@kingeke passing a data uri works...

```
<DocViewer
    documents={[{uri: 'data:application/pdf;base64,JVBERi0xLjQ ... UlRU9GCg==""}]}
    pluginRenderers={DocViewerRenderers}`
/>
````

**Comment by knaveenstar** [comment]
Its supports only Pdf, what application type should pass for docx and excel and PPT

**Comment by mattmogford-alcumus** [comment]
> Its supports only Pdf, what application type should pass for docx and excel and PPT

Current Renderable File Types

**Comment by knaveenstar** [comment]
Hi Alcumus,

I tried to use the defined current renderable fie types but its shows like this.
![image](https://user-images.githubusercontent.com/30283702/103122875-2ab6b880-46a8-11eb-8401-767fa0f93a0a.png)

**Comment by mattmogford-alcumus** [comment]
@knaveenstar 
Please see...
https://github.com/Alcumus/react-doc-viewer/issues/66
