### ISSUE TITLE
Excel,Docs Files Not supported in Base64 Input method

### ISSUE THREAD

**Issue by knaveenstar** [Alcumus/react-doc-viewer#66]
Hi Team,

I try to load the files using the Base64 method. such as below

  <DocViewer
    documents={[{uri: this.state.FileBase64}]}
    pluginRenderers={DocViewerRenderers} config={{header:{  disableHeader: true,
        disableFileName:true}}}/>

Its working fine for PDF and Images but not working for Docx,doc,xlsx files.

![image](https://user-images.githubusercontent.com/30283702/103097616-d838b600-462d-11eb-92e1-2b13d3bb8e97.png)

please help me to fix this issue

**Comment by mattmogford-alcumus** [comment]
The included renderer for Microsoft doc files etc. Only allow for URLs at this time.
You could create a custom renderer if required
________________________________

**Comment by knaveenstar** [comment]
HI Alucumus,

can you please help me create the custom render which supports base64 as input and support for office file such as word,excel and PPT

**Comment by mattmogford-alcumus** [comment]
@knaveenstar Hi,
There are ways to convert DocX to html and possibly pdf.
But there's not really a common way to locally render all ms docs. Each ms document type is very complex on its own and would take A LOT of manual conversion to display in the browser.

**Comment by shantha2210** [comment]
> HI Alucumus,
> 
> can you please help me create the custom render which supports base64 as input and support for office file such as word,excel and PPT

@knaveenstar hi,
do you find any solution for rendering docx, ppt files using base64, i had same scenario for my current work. any suggestions might be useful.

Thanks
Shanthakumar

**Comment by redmob** [comment]
Docs and excel files not working
