### ISSUE TITLE
File Not Found for .docx file types

### ISSUE THREAD

**Issue by cavinpabua** [Alcumus/react-doc-viewer#79]
![image](https://user-images.githubusercontent.com/53284605/111737367-74cfc480-88ba-11eb-8538-d5baf85d22bd.png)

All other file types can be viewed and working fine except docx

`<DocViewer documents={initVal} pluginRenderers={DocViewerRenderers} style={{width:"100%", minHeight:"600px", marginBottom:"30px"}} />`

All files are from firebase storage which is already enabled CORS

**Comment by mattmogford-alcumus** [comment]
@cavinpabua if you are providing a url to your document, then it would be a configuration issue on your firebase somehow
